global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 2.0
   publish_frequency: 2.0
   static_map: true
   transform_tolerance: 0.5
   rolling_window: true
   width: 100.0
   height: 100.0
   resolution: 0.05

   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

